sudo: required
language: python
python:
  - "3.6"

services:
  - docker

before_install:
  - pip install --upgrade pip
install:
  - pip install codecov

script:
  - make test/docker

after_success:
  - codecov
